apiVersion: app/v1
kind: Deployment
metadata:
  name: appdeployment
spec:
  replicas: 6
  matchLabel:
    Label: 
      app: appdeployment
  template:
      metadata: 
        Label:
          app: appdeployment
  spec:
    containers:
      - name: mycontainer
        id: 
        ports:
          - containerport: 5000

