apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: appdeployment
  template:
    metadata:
      labels:
        app: appdeployment
    spec:
      containers:
        - name: mycontainer
          image: 22251a1257it258/myapp:v1
          ports:
            - containerPort: 5000
